### ISSUE TITLE
github issues posted from cfr.tsv

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/csl-corrections#6]
date:	12/18/2019 19:52:27
dict:	wil
Lnum:	167
hw:	अक्षविद्
old:	विट् who knows.
new:	विद् who knows.
comm:	विट् 
email:	tvitaly1@yandex.ru

**Comment by drdhaval2785** [comment]
@funderburkjim and @gasyoun 
This issue is auto generated by a script from cfr.tsv via Github API.

This way we can keep track of errors to be corrected on github issue, rather than searching through the large cfr files.

I am yet to find out a way to ignore the issues posted earlier. But should not be a problem. Within a day or so, I will find out this.

Thereafter I can make this routine part of redo_cfr.sh.
This will make sure that every change appened to cfr.tsv is reflected in the issue section.

@funderburkjim As the changes are going to be made in csl-orig repository, I feel that the auto generated issues should also be in csl-orig repository, and not here. What do you say?

**Comment by drdhaval2785** [comment]
Necessary adjustments made to upload_github_issue.py file.

**Comment by funderburkjim** [comment]
Here is what I understand you to be doing:
* read cfr.tsv file 
* for each line, decide whether to accept the line for further processing
  * (not clear of criteria here)
* For an an 'accepted line',  
   * parse the line into fields and
   * post this to a new issue in csl-orig.

So, in effect, you aim to have each user-submission to be 'copied' to a csl-orig issue.

You are motivated to do this because of the awkwardness of working with cfr.tsv in a text editor.

Am I understanding you properly.

**Comment by funderburkjim** [comment]
## malformed user response records in cfr.tsv

There definitely are such 'bad' lines in cfr.tsv.   For instance, when I looked at cfr.tsv for the first time
a few days ago.  You can see examples of these bad lines by doing  a diff between the current and original cfr.tsv,  
`git diff HEAD e23efa -- app/correction_response/cfr.tsv`
Here are some of the **200** garbage lines submitted in under 2 minutes! 
```
+09/22/2019 16:41:57	MW	1	1	1	1	1'"	sample@email.tst
+09/22/2019 16:41:57	MW	1	1	1	1	Typo	sample@email.tst
+09/22/2019 16:41:57	MW	1	1	1	1	Typo	sample@email.tst
+09/22/2019 16:41:57	MW	1	1	1	1	LTEgT1IgMisxMjEtMTIxLTE9MCswKzArMSAtLSA=	sample@email.tst
+09/22/2019 16:41:57	MW	1	1	1	1	\	sample@email.tst
+09/22/2019 16:41:57	MW	1	1	1	1	LTEgT1IgMis5MjYtOTI2LTE9MCswKzArMQ==	sample@email.tst
+09/22/2019 16:41:57	MW	1	1	1	1	1
```

## How to handle such garbage ?

The only way I see is by examining cfr.tsv 'by hand'.
That's what I did.  I deleted by hand, these bad records.

**The posting to csl-orig should certainly not post such records from cfr.tsv.**

But once these records are filtered out,  I see no problem in posting.

**However, I'm less sure of the utility of this posting to csl-orig.**

It seems that the `dictionaries/xxx/xxx_correctionform.txt` files already have similar information.

## :Corrected mm/dd/yyyy 
There is still one reason that the cfr.tsv file  needs to be manually edited -- to update the status
when we have processed the correction.  

## cfr.tsv is cumulative
One virtue of cfr.tsv is that it is cumulative --  It has all the user-submitted corrections back to
2014!   Similarly, the files generated from cfr.tsv by cfr_adj.py  are cumulative  (e.g., 
* correctionform.txt  -- all of cfr.tsv
* dictionaries/xxx/xxx_correctionform.txt -- all of cfr.tsv for a given dictionary xxx.

## how to make cfr.tsv smaller.
We could divide up cfr.tsv into smaller files, perhaps by year.
Then, cfr_adj.py could be adjusted to, in effect, concatenate all these files when it generates its
'correctionform.txt' files.  

That way, the file 'app/correction_response/cfr.tsv' would contain  only a couple of hundred records
at any time.

**Comment by funderburkjim** [comment]
## enhancement suggestions

One advantage (in posting the user submissions as issues in csl-orig) is that the submissions could
be more easily reviewed by others or ourselves. 
If we depend only on the various correctionform.txt files,
then viewing such files would not be as obvious as is viewing the issues within csl-orig.  By posting
issues, we are leveraging the features of Github user interface, rather than relying solely on 
old-school usage of text editors.

## separate the issue generation from redo_cfr.sh
Reason:  sometimes cfr_adj.py will stop with an error condition.  This can be caused if, for example,
the user-submitted dictionary code is unknown.   In such a circumstance, we would want to correct
cfr.tsv by hand  before posting a new issue to csl-orig.

In other words, we would have a separate script (maybe, `post_cfr.sh`).

## what happens when the 'posting' script is rerun?
I was not clear on this.  Can it be rerun?  If it is repeated, what happens -- do duplicate issues
get posted?

## add labels to the issue.

When you look at the issues on Github,  you see the 'label' assigned to the issue.
It would be helpful if there were a 'completed' or 'installed' label, which could be automatically
generated,  along with the text of the updated 'status'

This adding of labels and changing of status could be what happens when it is rerun.
But if nothing has changed in a given line of cfr.tsv since the last rerun of post_cfr.txt,  then there should be no new posting in the csl-orig issue.

## don't show user email in issue text
I think that only cfr.tsv should have the email address.   i.e., we should keep it only in this obscure
location, for user privacy concerns.   You'll note only an abbreviated user name (not the entire
email address) is printed in the correctionform.txt files.

**Comment by drdhaval2785** [comment]
@funderburkjim

Regarding your comment at https://github.com/sanskrit-lexicon/csl-corrections/issues/6#issuecomment-567751106
You understood it quite well that the motivation is to copy the correction submissions to csl-orig github issue from unprocessed entries from cfr.tsv file.

`malformed items not to be pushed` - I see no problem if they are also pushed. We can close the issue later on, and delete the line from cfr.tsv.

`what is the usefulness of issues` 
Currently cfr.tsv does not allow for discussions of difficult cases. 
Recently I stumbled upon 8 such cases in MW where the resolution was above my understanding / capacities.
I could tag them 'help wanted'. https://github.com/sanskrit-lexicon/csl-orig/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22+mw%3A 
Now anyone can help me in resolving those cases, including you.

**Comment by drdhaval2785** [comment]
# What if rerun

The issues would not be posted afresh. Let us assume that there are 4 new entries since we last ran the code. Last line which has been processed from cfr.tsv is stored in https://github.com/sanskrit-lexicon/csl-corrections/blob/master/last_cfr_line.txt . All the lines of cfr.tsv are ignored till this line. 
Once the issues are posted for next let's say pending 4 lines, the last_cfr_line.txt is updated. Then on subsequent run, there would be no effect.

# Separate issue_generation from redo_cfr.sh

I see no issue in doing so.
`python upload_github_issue.py app/correction_response/cfr.tsv` is the code to run. We can remove this from redo_cfr.sh.

# No emails in issues

I agree. Will remove.

**Comment by drdhaval2785** [comment]
https://github.com/sanskrit-lexicon/csl-corrections/blob/master/post_github_issues.sh is a separate script for uploading github issues from unprocessed cfr.tsv.
Changes made to remove emails from issues.

**Comment by gasyoun** [comment]
> email: tvitaly1@yandex.ru

Would remake it at least to tvitaly1 @ yandex.ru or something email harvesters will not find easy.

**Comment by funderburkjim** [comment]
> cfr.tsv does not allow for discussions of difficult cases

Agree.

**Comment by drdhaval2785** [comment]
Closing this issue. Github issues are posted by post_github_issues.sh

**Comment by funderburkjim** [comment]
> Once the issues are posted for next let's say pending 4 lines, the last_cfr_line.txt is updated

last_cfr_line.txt  contains line number relative to app/correction_response/cfr.tsv.

Currently the number in last_cfr_line.txt is 24546.
The line count in app/correction_response/cfr.tsv is the same, (wc -l shows 24546).

The upload_github_issue.py program logic is clever; the following describes the logic pertaining
to which lines of cfr.tsv generate posts.

A line of cfr.tsv generates a post to issues of csl-orig if:
* the INDEX of the line exceeds 24546
* AND the status field of the line does not contain a colon
   * Dhaval or I manually add a ': Corrected mm/dd/yyyy' string to this status field when we've completed a correction.

When all lines of cfr.tsv have been processed, the program writes a new value to last_cfr_line.txt;
this new value is 1 more than the index value of the last line of cfr.tsv, which is same as the
number of lines in cfr.tsv.
 
In the current setting,  rerunning the program would yield NO new issue postings to csl-orig,
*since the INDEX of no line of cfr.tsv exceeds 24546*.

That eases my mind regarding
* reruns of the program. -- reruns don't cause problems
* how last_cfr_line.txt is maintained -- the program maintains this.  Dhaval only had to set
the value in last_cfr_line.txt before the program was run the first time.

**Comment by funderburkjim** [comment]
## requests library requirement

upload_github_issue.py uses the 'requests' library.
The python being used needs to have the 'requests' module installed.
AFAIK, 'requests' must be installed (pip install requests) ; it is not part of standard library.

Both python (= python2) and python3 at Cologne have requests installed by the sys-admin.

> We need to add 'pip install requests' to the required software list in our documentation
    of csl-corrections repository.

**Comment by funderburkjim** [comment]
## environment variables for uploading to github

The upload_github_issue.py has another nice feature that was new to me, and that will have 
utility in other github automation programs.  

When a program posts something  (such as an issue) using the Github api,  that program must
provide authentication.  

## An insecure solution
When I have done this (like for the Sanskrit in Greek project),  the code looked like
```
headers = {'Authorization':'token API_TOKEN_FOR_GITHUB'}
requests.post(url,headers=headers,data=json.dumps(payload))
```
The key point is that the API token was shown in plain text as part of the program code.
This could potentially be a security risk, for example if the program were itself part of a Github
repository.

## Environment codes better
Dhaval's code uses environment variables:
```
username = os.environ['GITHUB_USER']
password = os.environ['GITHUB_PASSWORD']
print(entry)
s = requests.Session()
s.auth = (username, password)
r = s.post('https://api.github.com/repos/sanskrit-lexicon/csl-orig/issues', json.dumps(entry))
```

So the code file does not show the actual values of username and password.
The code only assumes that two environment variables have been set when the program is run.

## Setting the environment variables
[Stackoverflow](https://stackoverflow.com/questions/34169721/set-an-environment-variable-in-git-bash) shows how to set an environment variable in git-bash.
Here is a session from git-bash:
```
Jim@Jim-Dell MINGW64 /c/xampp/htdocs/cologne/csl-corrections (master)
$ export GITHUB_USER='SANTA'

Jim@Jim-Dell MINGW64 /c/xampp/htdocs/cologne/csl-corrections (master)
$ echo $GITHUB_USER  
SANTA

Jim@Jim-Dell MINGW64 /c/xampp/htdocs/cologne/csl-corrections (master)
$ export GITHUB_PASSWORD='CLAUS'
```

## python test
Here is a simple example of referencing these environment variables from within python, using
an interactive session.
```
Jim@Jim-Dell MINGW64 /c/xampp/htdocs/cologne/csl-corrections (master)
$ python -i
Python 2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.environ['GITHUB_USER']
'SANTA'
>>> quit()
```

## Use .bashrc to further automate
With git-bash,  we can set environment variables to be always available, by placing the commands
in the ~/.bashrc.   

Where is .bashrc ?  In git-bash terminal
```
$ ls ~/.bashrc
/c/Users/Jim/.bashrc
```
So, in my case, I am user 'Jim' and I already have a `.bashrc` file, If I had no `.bashrc` file, I would
create it in `c:/Users/Jim`.
Then using a text editor, these two lines would be added to `.bashrc`:
```
export GITHUB_USER='SANTA'
export GITHUB_PASSWORD='CLAUS'
```
Now, the next time I open a git-bash terminal, these environment variables will be set, so I won't
need to manually set them.  The values can be examined in git-bash
```
Jim@Jim-Dell MINGW64 /
$ echo $GITHUB_USER
SANTA

Jim@Jim-Dell MINGW64 /
$ echo $GITHUB_PASSWORD
CLAUS
```

**Comment by gasyoun** [comment]
> The upload_github_issue.py program logic is clever

Clever indeed.

> next time I open a git-bash terminal, these environment variables will be set, so I won't need to manually set them

Automation they call it )

**Comment by funderburkjim** [comment]
Note:  I  created the  personal access token  with 'repo scope' selected.
This seems to work fine for upload_github_issue.py.

**Comment by drdhaval2785** [comment]
Great.
