### ISSUE TITLE
how do I update cfr.tsv?

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/csl-corrections#81]
@funderburkjim 
Kindly guide how I can update cfr.tsv to see the user submitted corrections?
I submitted a correction in SKD dictionary under headword 'devaH' 
I do not know how I can get the latest cfr.tsv and make changes based on user feedback.
Request you to guide me on this front.

**Comment by drdhaval2785** [comment]
Can I draw your attention to this question @funderburkjim? 
If necessary, you can send the reply via mail too.

**Comment by funderburkjim** [comment]
This is always a tedious task, with lots of intermediate steps.  

I last processed user corrections on June 21.

## step 1
As you probably know,  submission of a user correction appends a line to the  cfr.tsv file at Cologne. 

The first step thus pushes the Cologne csl-corrections repository to Github.  

In anticipation of your handling the pending corrections,  I have just done this push.  Ideally, this
push should be done close to the time the corrections will be processed.  If you don't plan to attend
to the corrections for several days, then I'll redo step 1 again, before you begin.

## step 2
Unfortunately, there are often a few 'spam' submissions.
Thus, it is advisable  to edit the cfr.tsv file manually, go to the bottom, and manually delete such spam lines.   Unprocessed lines are at the bottom.  A processed line is identified by
having the last field (user-email field, sometimes empty)  with ': DATE ACTION' added.

## step 3
Run 'post_github_issues.sh' script.
   This is code you wrote which generates issues in csl-orig, one per each line added since the last run.

## step 4
Run 'redo_cfr.sh' .   This 
a) regenerates the correctionform.txt file 
b) regenerates the individual correctionform files:  dictionaries/xxx/xxx_correctionform.txt
c) prints out a list of work to (such as '5 corrections for mw', '2 corrections for ap90', etc.

Note: this redo_cfr.sh can be run multiple times.

## step 5 (iterative)
I keep open in one editor window cfr.tsv, for posting the ': DATE ACTION' messages.
I also open in a sticky note a list user-dictionaries for which thank you notes are sent as very last step,
after corrections have been installed at Cologne.

I generally pick one dictionary xxx with corrections to process from the printed list.
Then open dictionaries/xxx/xxx_correctionform.txt  and process the items at top of file.
For each item,
  a) decide what needs to be done.
  b) make the necessary correction in csl-orig/v02/xxx.txt
  b1)  For a print change, add a line to dictionaries/xxx/xxx_printchange.txt.
  c) add comment to the csl-orig issue generated in step 3. Close issue as needed.
  d) update the corresponding line in cfr.tsv
  e) add to the list of required 'thank you' messages for the user
     I actually update a 'form letter' for this correction, see below
  f) push the csl-orig correction   [This can be done item by item, or dictionary by dictionary]
Repeat step 5 until all corrections done.

## step 6  Finishing
run 'redo_cfr.sh' a final time, so all the corrections reflected in the xxx_correctionform.txt files
add, commit, push csl-corrections.
At Cologne ([I  will need to do this, unless you have gotten your ssh login at Cologne)
  pull csl-corrections
  pull csl-orig
  do updates in csl-pywork/v02 for the dictionaries changed
Write thank-you notes to the users.

I generally use a form-letter to simplify the thank-you note process:
```
Dear Friend -

  Thank you for the correction to xxx dictionary.

  The correction has been installed.

Regards,

 Jim Funderburk  

You wrote:
```
After the 'you wrote' I generally copy/paste the info in the item of dictionaries/xxx/xxx_correctionform.txt.

**Comment by funderburkjim** [comment]
It would be a help if you join this effort.  Maybe we could process user corrections more frequently,
taking turns.

**Comment by funderburkjim** [comment]
Am beginning the catch-up since June 21.
After having done step4, I opened several windows, and am beginning to work with the 26 mw corrections that are pending.  Here's the desktop.

![image](https://user-images.githubusercontent.com/6393033/135530465-68dff2d4-dce3-480f-a298-b9ee07b5664d.png)

**Comment by drdhaval2785** [comment]
Wonderful to see you jam packed screenshot.

**Comment by drdhaval2785** [comment]
This issue is now treated solved in light of the file readme_howto.txt.
